#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains

domain=$1
subdomain=$2

function display_info {
    subdomain=$1
    record_type=$2
    destination=$3
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
  
    display_info "www" "$(dig +short www.$domain | awk 'NR==1{print "A"}')" "$(dig +short www.$domain)"
    display_info "lb-01" "$(dig +short lb-01.$domain | awk 'NR==1{print "A"}')" "$(dig +short lb-01.$domain)"
    display_info "web-01" "A" "$(dig +short web-01.$domain)"
    display_info "web-02" "A" "$(dig +short web-02.$domain)"
else
  
    record_type=$(dig +short $subdomain.$domain | awk 'NR==1{print "A"}')
    destination=$(dig +short $subdomain.$domain)
    display_info "$subdomain" "$record_type" "$destination"
fi

